
package film;

import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author Dana
 */
public class formFilm extends javax.swing.JFrame {
    
    String judulKolom[]={"Kode Film", "Judul", "Genre", "Tahun", "Asal"};
    String sqlFilm="SELECT*FROM film";
    int lebarKolom[]={100,300,100,60,200};

    /**
     * Creates new form formFilm
     */
    public formFilm() {
        initComponents();
        
        this.setLocationRelativeTo(null);
        new ConfigDB().tampilTabel(judulKolom, sqlFilm, jTable1);    
        new ConfigDB().aturLebarKolom(jTable1, lebarKolom);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtKode = new javax.swing.JTextField();
        txtJudul = new javax.swing.JTextField();
        cmbGenre = new javax.swing.JComboBox<>();
        txtTahun = new javax.swing.JTextField();
        txtAsal = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Kode Film");

        jLabel2.setText("Judul");

        jLabel3.setText("Genre");

        jLabel4.setText("Tahun");

        jLabel5.setText("Asal Negara");

        cmbGenre.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { ".: Pilih Genre :.", " Action ", "Adventure ", "Animation ", "Biography ", "Comedy ", "Crime ", "Documentary", " Drama ", "Family ", "Fantasy", " History ", "Horror ", "Musical ", "Mystery", " Sport ", "Thriller ", "War ", "Western" }));

        jButton1.setText("Simpan");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Ubah");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Hapus");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Clear");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addGap(51, 51, 51)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtKode)
                            .addComponent(txtJudul)
                            .addComponent(cmbGenre, 0, 213, Short.MAX_VALUE)
                            .addComponent(txtTahun)
                            .addComponent(txtAsal))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton4)))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtKode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtJudul, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cmbGenre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtTahun, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtAsal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3)
                    .addComponent(jButton4)
                    .addComponent(jButton2)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(109, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            if (txtKode.getText().isEmpty()) {
                JOptionPane.showMessageDialog(null, "Kode film belum diisi");
                txtKode.requestFocus();
            } else if (txtJudul.getText().isEmpty()) {
                JOptionPane.showMessageDialog(null, "Judul film belum diisi");
                txtJudul.requestFocus();
            } else if (String.valueOf(cmbGenre.getSelectedItem())== "..Pilih Judul..") {
                JOptionPane.showMessageDialog(null, "Genre film belum diisi");
                cmbGenre.requestFocus();
            } else if (txtTahun.getText().isEmpty()) {
                JOptionPane.showMessageDialog(null, "Tahun belum diisi");
                txtTahun.requestFocus();
            } else if (txtAsal.getText().isEmpty()) {
                JOptionPane.showMessageDialog(null, "Asal Negara film belum diisi");
                txtAsal.requestFocus();
         
            } else if(new ConfigDB().duplikasiData("film", "KodeFilm", txtKode.getText())==true) {
                JOptionPane.showMessageDialog(null, "Kode Film sudah terdaftar");
                Statement st = new ConfigDB().koneksi.createStatement();
                ResultSet rs = st.executeQuery("SELECT*FROM film WHERE KodeFilm='"+txtKode.getText()+"'");   
                if (rs.next()) {
                    txtJudul.setText(rs.getString("Judul"));
                    cmbGenre.setSelectedItem(String.valueOf(rs.getString("Genre")));
                    txtTahun.setText(rs.getString("tahun"));
                    txtAsal.setText(rs.getString("asal"));
                    
                }
            } else {
                String SQL = "INSERT INTO film VALUES ("
                        + "'"+txtKode.getText()+"'"
                        + ",'"+txtJudul.getText()+"'"
                        + ",'"+String.valueOf(cmbGenre.getSelectedItem())+"'"
                        + ",'"+txtTahun.getText()+"'"
                        + ",'"+txtAsal.getText()+"')";
                new ConfigDB().simpanData(SQL);
                new ConfigDB().tampilTabel(judulKolom, sqlFilm, jTable1);
                new ConfigDB().aturLebarKolom(jTable1, lebarKolom);
            }
        } catch (Exception e) {
            
        }    
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
            try {
     if (
        (txtKode.getText().isEmpty()) && (txtJudul.getText().isEmpty()) &&
        (txtAsal.getText().isEmpty()) && (txtTahun.getText().isEmpty()) &&
        (String.valueOf(cmbGenre.getSelectedItem())==".: Pilih Judul :.")
        )
     {
        JOptionPane.showMessageDialog(null,"Silahkan Pilih Data dulu untuk proses Ubah");
        jTable1.requestFocus();
      } else
     {
            String SQL="UPDATE film SET judul='"+txtJudul.getText()+"', genre='"+String.valueOf(cmbGenre.getSelectedItem())
            +"', tahun='"+txtTahun.getText()+"', asal='"+txtAsal.getText()+"'WHERE KodeFilm='"+txtKode.getText()+"'";
            new ConfigDB().ubahData(SQL);
            new ConfigDB().tampilTabel(judulKolom, sqlFilm, jTable1);
            new ConfigDB().aturLebarKolom(jTable1, lebarKolom);
            }
     } catch (Exception e)
        {
     System.out.print(e.toString());
     }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
                try {
            if(
              (txtKode.getText().isEmpty()) && (txtJudul.getText().isEmpty()) &&
              (txtAsal.getText().isEmpty()) && (txtTahun.getText().isEmpty()) &&
              (String.valueOf(cmbGenre.getSelectedItem())==".:Pilih Genre:.")
              )
            {
                JOptionPane.showMessageDialog(null, "Silahkan Pilih Data dulu untuk proses Hapus");
                jTable1.requestFocus();
            }else
            {
                String SQL="DELETE FROM film WHERE KodeFilm='"+txtKode.getText()+"'";
                new ConfigDB().hapusData(SQL);
                new ConfigDB().tampilTabel(judulKolom, sqlFilm, jTable1);
                new ConfigDB().aturLebarKolom(jTable1, lebarKolom);
            }
        } catch (Exception e) {
            System.out.print(e.toString());
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        txtKode.setText(null);
        txtJudul.setText(null);
        txtAsal.setText(null);
        txtTahun.setText(null);
        cmbGenre.setSelectedItem(String.valueOf(".:Pilih Genre:."));
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        try {
            int baris = jTable1.getSelectedRow();
             txtKode.setText(String.valueOf(jTable1.getValueAt(baris,0)));         
             txtJudul.setText(String.valueOf(jTable1.getValueAt(baris,1)));         
             cmbGenre.setSelectedItem(String.valueOf(jTable1.getValueAt(baris,2)));         
             txtTahun.setText(String.valueOf(jTable1.getValueAt(baris,3)));         
             txtAsal.setText(String.valueOf(jTable1.getValueAt(baris,4))); 
        } catch (Exception e) {
            System.out.print(e.toString());
        }
    }//GEN-LAST:event_jTable1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(formFilm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(formFilm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(formFilm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(formFilm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new formFilm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cmbGenre;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txtAsal;
    private javax.swing.JTextField txtJudul;
    private javax.swing.JTextField txtKode;
    private javax.swing.JTextField txtTahun;
    // End of variables declaration//GEN-END:variables
}
